<?php
$paymentInfo = $block->getPaymentInfo();
$src = $block->getPluginSrc();
$paymentId = $block->getPaymentId();
$env = $block->getEnv();
if ($block->getPaymentMethod() === 'talopay_transfer'): ?>
   <button type="button" class="action primary btn-talopay-transfer" data-trigger="trigger">
        <span >Ver datos para transferir</span>
    </button>
    <div data-bind="mageInit: {
        'Magento_Ui/js/modal/modal':{
            'type': 'popup',
            'modalClass': 'modaltransfer',
            'title': 'Pagá por transferencia',
            'trigger': '[data-trigger=trigger]',
            'responsive': true,
        }}">
        <div id="talopay-order" data-paymentid="<?= $block->escaper->escapeHtml($paymentId) ?>"></div>
        <script>
            setTimeout(() => {
                require(["jquery", "TaloPay_<?= $env ?>"], function($, pym) {});
            }, 5000);
        </script>
    </div>
<?php endif; ?>